[package]
name = "subway_map"
version = "0.1.0"
authors = ["Emily Crandall Fleischman <emilycf@mit.edu>"]
build = "build.rs"

[build-dependencies]
lalrpop = "0.13.1"

[dependencies]
lalrpop-util = "0.13.1"
lazy_static = "0.2.9"
ordered-float = "0.5.0"
regex = "0.2.1"
